In [68]:
import tensorflow as tf

In [104]:
from tensorflow import keras


In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [70]:
data=pd.read_csv("insurence.csv")

In [71]:
data.head()

age  affordability  have_insurance
0   22              1               0
1   25              0               0
2   47              1               1
3   52              0               0
4   46              1               1

In [72]:
type(data)

pandas.core.frame.DataFrame

In [73]:
x=np.array(data[["age","affordability"]])

In [74]:
x[0:4]

array([[22,  1],
       [25,  0],
       [47,  1],
       [52,  0]])

In [75]:
y=np.array(data["have_insurance"])

In [76]:
y[0:4]

array([0, 0, 1, 0])

In [77]:
y.shape

(50,)

In [87]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [88]:
x_train.shape

(40, 2)

In [89]:
x_test.shape

(10, 2)

In [90]:
x_train[0:5]

array([[27,  0],
       [46,  1],
       [30,  1],
       [62,  1],
       [52,  0]])

In [91]:
x_test[0:5]

array([[34,  1],
       [57,  1],
       [54,  1],
       [60,  0],
       [33,  1]])

In [97]:
x_test_scalled=x_test.copy()
x_train_scalled=x_train.copy()
x_test_scalled = x_test_scalled.astype(float)
x_train_scalled = x_train_scalled.astype(float)

In [100]:
x_train_scalled[:, 0] = x_train_scalled[:, 0] / 100
x_test_scalled[:, 0] = x_test_scalled[:, 0] / 100

In [ ]:
x_train_scalled[0:5]


array([[0.27, 0.  ],
       [0.46, 1.  ],
       [0.3 , 1.  ],
       [0.62, 1.  ],
       [0.52, 0.  ]])

In [101]:
x_test_scalled[0:5]

array([[0.34, 1.  ],
       [0.57, 1.  ],
       [0.54, 1.  ],
       [0.6 , 0.  ],
       [0.33, 1.  ]])

In [108]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

In [111]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [117]:
model.fit(x_train_scalled,y_train,epochs=300)

Epoch 1/300


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6625 - loss: 0.6277
Epoch 2/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6521 - loss: 0.6356
Epoch 3/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6729 - loss: 0.6314 
Epoch 4/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6625 - loss: 0.6364
Epoch 5/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6729 - loss: 0.6299
Epoch 6/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6833 - loss: 0.6235
Epoch 7/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6625 - loss: 0.6286
Epoch 8/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6729 - loss: 0.6285
Epoch 9/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6417 - loss: 0.6539
Epoch 10/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6729 - loss: 0.6264
Epoch 11/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6625 - loss: 0.6363
Epoch 12/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6417 - loss: 0.6420


In [118]:
predict=model.predict(x_test_scalled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


In [119]:
predict

array([[0.8437952 ],
       [0.9099948 ],
       [0.90307003],
       [0.78821695],
       [0.8401693 ],
       [0.928166  ],
       [0.62805015],
       [0.9122021 ],
       [0.88778275],
       [0.58251023]], dtype=float32)

In [116]:
y_test

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [120]:
model.get_weights()

[array([[2.7253444],
        [1.0811207]], dtype=float32),
 array([-0.32099593], dtype=float32)]