In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
data=pd.read_csv("insurence.csv")

In [5]:
data.head()

age  affordability  have_insurance
0   22              1               0
1   25              0               0
2   47              1               1
3   52              0               0
4   46              1               1

In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
x=np.array(data[["age","affordability"]])

In [8]:
x[0:4]

array([[22,  1],
       [25,  0],
       [47,  1],
       [52,  0]])

In [9]:
y=np.array(data["have_insurance"])

In [10]:
y[0:4]

array([0, 0, 1, 0])

In [11]:
y.shape

(50,)

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [13]:
x_train.shape

(40, 2)

In [14]:
x_test.shape

(10, 2)

In [15]:
x_train[0:5]

array([[27,  0],
       [46,  1],
       [30,  1],
       [62,  1],
       [52,  0]])

In [16]:
x_test[0:5]

array([[34,  1],
       [57,  1],
       [54,  1],
       [60,  0],
       [33,  1]])

In [17]:
x_test_scalled=x_test.copy()
x_train_scalled=x_train.copy()
x_test_scalled = x_test_scalled.astype(float)
x_train_scalled = x_train_scalled.astype(float)

In [18]:
x_train_scalled[:, 0] = x_train_scalled[:, 0] / 100
x_test_scalled[:, 0] = x_test_scalled[:, 0] / 100

In [19]:
x_train_scalled[0:5]


array([[0.27, 0.  ],
       [0.46, 1.  ],
       [0.3 , 1.  ],
       [0.62, 1.  ],
       [0.52, 0.  ]])

In [20]:
x_test_scalled[0:5]

array([[0.34, 1.  ],
       [0.57, 1.  ],
       [0.54, 1.  ],
       [0.6 , 0.  ],
       [0.33, 1.  ]])

In [21]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

c:\Users\praka\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [23]:
model.fit(x_train_scalled,y_train,epochs=300)

Epoch 1/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.5813 - loss: 0.6522 
Epoch 2/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5500 - loss: 0.6780
Epoch 3/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5813 - loss: 0.6427
Epoch 4/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5708 - loss: 0.6503
Epoch 5/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5813 - loss: 0.6520
Epoch 6/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5917 - loss: 0.6403
Epoch 7/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5708 - loss: 0.6462
Epoch 8/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5813 - loss: 0.6672
Epoch 9/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5708 - loss: 0.6561
Epoch 10/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5708 - loss: 0.6562
Epoch 11/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5708 - loss: 0.6583
Epoch 12/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5604 - l

In [24]:
predict=model.predict(x_test_scalled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


In [25]:
predict

array([[0.69003296],
       [0.73461163],
       [0.7290344 ],
       [0.5586292 ],
       [0.6880032 ],
       [0.75089717],
       [0.49022353],
       [0.7364543 ],
       [0.71766174],
       [0.4736692 ]], dtype=float32)

In [26]:
y_test

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [27]:
model.get_weights()

[array([[0.94728106],
        [0.81096566]], dtype=float32),
 array([-0.33276805], dtype=float32)]